---
# tasks file for docker
- import_tasks: packages.yml
- import_tasks: platform.yml
- import_tasks: users.yml
- import_tasks: languages.yml
  become: true
  become_user: ubuntu
- import_tasks: monitoring.yml
  become: true
  become_user: ubuntu
