---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: test-instance
    image: ami-029bb09da31cbfdfc
    instance_type: t2.micro
    vpc_subnet_id: subnet-fda20880
    region: eu-central-1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: E501
