---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: test-instance
    image: ami-0b5a2788ae89f99ff
    instance_type: t2.micro
    vpc_subnet_id: subnet-05e9574d
    region: eu-west-1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
