# frozen_string_literal: true

source "https://rubygems.org"

# Added at 2019-03-19 13:20:13 +0100 by becker:
gem "inspec", "~> 5.0", ">= 5.22.3"

# Added at 2019-03-19 13:28:25 +0100 by becker:
gem "rubocop", "~> 1.54.0"

