# frozen_string_literal: true

source "https://rubygems.org"

# Added at 2019-03-19 13:20:13 +0100 by becker:
gem "inspec", "~> 3.7"

# Added at 2019-03-19 13:28:25 +0100 by becker:
gem "rubocop", "~> 0.66.0"

